# Generated by Django 3.1.6 on 2021-03-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
