# Generated by Django 3.1.6 on 2021-03-17 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_auto_20210317_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extenduser',
            new_name='Profile',
        ),
    ]
