# Generated by Django 3.1.6 on 2021-03-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210317_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
