# Generated by Django 3.1.6 on 2021-05-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210317_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctordata',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50)),
                ('sid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='specialist',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
            ],
        ),
    ]
