# Generated by Django 3.1.6 on 2021-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210516_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
