# Generated by Django 3.1.6 on 2021-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_patient_appointment_doctorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='username',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
