# Generated by Django 3.1.6 on 2021-05-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordata',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
